### ISSUE TITLE
The plugin is not compatible with Gradle 7.x in strict mode

### ISSUE THREAD

**Issue by nskvortsov** [apache/grails-gradle-plugin#184]
With Gradle 7.x running with strict warning mode
> org.gradle.warning.mode= fail

Grails plugin can not be applied:

```
The AbstractArchiveTask.appendix property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the archiveAppendix property instead. See https://docs.gradle.org/7.6/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:appendix for more details.
	at org.gradle.api.tasks.bundling.AbstractArchiveTask.setAppendix(AbstractArchiveTask.java:304)
	at org.gradle.api.tasks.bundling.Jar_Decorated.setAppendix(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.api.tasks.bundling.Jar_Decorated.setProperty(Unknown Source)
	at org.grails.gradle.plugin.core.GrailsGradlePlugin$_createPathingJarTask_closure20.doCall(GrailsGradlePlugin.groovy:587)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
```

**Comment by guillermocalvo** [comment]
Fixed by #206
